# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Compile Contracts

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  compile-contracts:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: Compile
        run: scripts/compile_contracts.sh

      - name: Commit changes
        run: |
          git config --local user.email "bot@citizenwallet.xyz"
          git config --local user.name "citizenwallet-bot"

      - uses: phish108/autotag-action@v1.1.55
        id: tagger
        with:
          github-token: ${{ secrets.GITHUB_TOKEN}}
          with-v: "true"
          dry-run: "true"

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[action] compile contracts"
          commit_user_name: citizenwallet-bot
          commit_user_email: bot@citizenwallet.xyz
          tagging_message: "${{ steps.tagger.outputs.new-tag }}"
